"""Core state machine for Agent Coordination Kit.

The module intentionally uses only Python stdlib so it can run in constrained
developer machines without installing the official MCP SDK first.
"""

import fnmatch
import glob
import html
import json
import os
import socket
import time
import uuid
from contextlib import contextmanager
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


GENERATED_MARKER = "<!-- generated by Agent Coordination Kit; do not edit directly -->"
FIXED_MARKDOWN_FILES = ("AGENTS.md", "TASK_BOARD.md", "DECISIONS.md", "HANDOFF_LOG.md")
ROLE_VALUES = {"coordinator", "frontend", "backend", "langflow", "tester", "docs", "custom"}
TASK_STATUSES = {"todo", "in_progress", "blocked", "review", "done"}
PRIORITIES = {"P0", "P1", "P2"}
RELEASE_REASONS = {"done", "abandoned", "expired", "manual"}
REVIEW_RESULTS = {"approved", "rejected"}


class CoordinatorError(Exception):
    """Base error with optional structured details."""

    def __init__(self, message: str, **details: Any):
        super().__init__(message)
        self.details = details


class RevisionConflictError(CoordinatorError):
    def __init__(self, expected_revision: int, latest_revision: int):
        super().__init__(
            "revision conflict",
            expected_revision=expected_revision,
            latest_revision=latest_revision,
        )
        self.expected_revision = expected_revision
        self.latest_revision = latest_revision


class ConflictError(CoordinatorError):
    def __init__(self, message: str, conflicts: Optional[List[Dict[str, Any]]] = None):
        super().__init__(message, conflicts=conflicts or [])
        self.conflicts = conflicts or []


class LockConflictError(ConflictError):
    pass


class InvalidOperationError(CoordinatorError):
    pass


def utc_now() -> str:
    return datetime.utcnow().replace(microsecond=0).isoformat() + "Z"


def parse_time(value: str) -> datetime:
    if value.endswith("Z"):
        value = value[:-1]
    return datetime.fromisoformat(value)


def add_minutes(minutes: float) -> str:
    return (datetime.utcnow() + timedelta(minutes=minutes)).replace(microsecond=0).isoformat() + "Z"


def new_id(prefix: str) -> str:
    return "%s_%s" % (prefix, uuid.uuid4().hex[:12])


def has_glob(value: str) -> bool:
    return any(ch in value for ch in "*?[")


def normalize_repo_path(path: str) -> str:
    if not path or not isinstance(path, str):
        raise ValueError("path must be a non-empty string")
    path = path.replace("\\", "/").strip()
    if os.path.isabs(path) or path.startswith("/"):
        raise ValueError("absolute paths are not allowed: %s" % path)
    parts = [p for p in path.split("/") if p not in ("", ".")]
    if any(p == ".." for p in parts):
        raise ValueError("path traversal is not allowed: %s" % path)
    if not parts:
        raise ValueError("path must not point to repo root")
    return "/".join(parts)


def normalize_paths(paths: Iterable[str]) -> List[str]:
    return [normalize_repo_path(p) for p in paths]


def safe_code_block(value: Optional[str]) -> str:
    text = html.escape(value or "", quote=False)
    text = text.replace("```", "`\u200b``")
    return "```text\n%s\n```" % text


def blank_state(goal: str = "") -> Dict[str, Any]:
    return {
        "revision": 0,
        "last_event_id": None,
        "goal": goal,
        "agents": [],
        "tasks": [],
        "claims": [],
        "decisions": [],
        "handoffs": [],
    }


class CoordinatorStore:
    def __init__(self, root: Path, docs_dir: Optional[Path] = None, lock_ttl_seconds: int = 30):
        self.root = Path(root).resolve()
        self.coord_dir = self.root / ".agent-coordinator"
        self.events_path = self.coord_dir / "events.jsonl"
        self.state_path = self.coord_dir / "state.json"
        self.lock_path = self.coord_dir / ".lock"
        self.docs_dir = Path(docs_dir).resolve() if docs_dir else self.coord_dir
        self.lock_ttl_seconds = lock_ttl_seconds
        self.server_owner = "ack-%s-%s" % (socket.gethostname(), os.getpid())

    def init_workspace(self, goal: str = "", expected_revision: Optional[int] = None) -> Dict[str, Any]:
        self.coord_dir.mkdir(parents=True, exist_ok=True)
        self.docs_dir.mkdir(parents=True, exist_ok=True)
        if self.events_path.exists() and self.events_path.stat().st_size > 0:
            state = self.load_state()
            if expected_revision is not None and state["revision"] != expected_revision:
                raise RevisionConflictError(expected_revision, state["revision"])
            return state
        state = blank_state()
        event = self._make_event("workspace_initialized", state, {"goal": goal})
        self._append_events_and_write_state(state, [event])
        return self.load_state()

    def load_state(self) -> Dict[str, Any]:
        self.coord_dir.mkdir(parents=True, exist_ok=True)
        events = self._read_events()
        expected_revision = events[-1]["revision"] if events else 0
        expected_last_id = events[-1]["id"] if events else None
        if self.state_path.exists():
            try:
                state = json.loads(self.state_path.read_text(encoding="utf-8"))
                if state.get("revision") == expected_revision and state.get("last_event_id") == expected_last_id:
                    return state
            except Exception:
                pass
        state = self._replay(events)
        self._atomic_write_json(self.state_path, state)
        return state

    def get_context_bundle(self, role: Optional[str] = None, scope: Optional[List[str]] = None) -> Dict[str, Any]:
        state = self.load_state()
        normalized_scope = normalize_paths(scope or []) if scope else []
        tasks = state["tasks"]
        claims = [c for c in state["claims"] if c["status"] == "active"]
        if role:
            agent_ids = {a["id"] for a in state["agents"] if a["role"] == role}
            tasks = [t for t in tasks if t.get("owner") in agent_ids or self._scope_matches(normalized_scope, t["scope"])]
            claims = [c for c in claims if c["agent_id"] in agent_ids or self._claim_matches_scope(c, normalized_scope)]
        return {
            "goal": state["goal"],
            "revision": state["revision"],
            "agents": state["agents"],
            "tasks": tasks,
            "active_claims": claims,
            "decisions": state["decisions"],
            "handoffs": state["handoffs"],
        }

    def register_agent(
        self,
        role: str,
        display_name: str,
        scope: List[str],
        expected_revision: Optional[int] = None,
    ) -> Dict[str, Any]:
        if role not in ROLE_VALUES:
            raise ValueError("invalid role: %s" % role)
        normalized_scope = normalize_paths(scope)
        agent_id = new_id("agent")
        now = utc_now()
        payload = {
            "agent": {
                "id": agent_id,
                "role": role,
                "display_name": display_name,
                "scope": normalized_scope,
                "status": "active",
                "created_at": now,
                "last_heartbeat_at": now,
            }
        }
        return self._single_event_write("agent_registered", payload, "agents", agent_id, expected_revision)

    def heartbeat_agent(self, agent_id: str) -> Dict[str, Any]:
        with self._locked():
            state = self.load_state()
            now = utc_now()
            found = False
            for agent in state["agents"]:
                if agent["id"] == agent_id:
                    agent["last_heartbeat_at"] = now
                    agent["status"] = "active"
                    found = True
            if not found:
                raise InvalidOperationError("agent not found: %s" % agent_id)
            for claim in state["claims"]:
                if claim["agent_id"] == agent_id and claim["status"] == "active":
                    claim["heartbeat_at"] = now
                    claim["updated_at"] = now
            self._atomic_write_json(self.state_path, state)
            return {"agent_id": agent_id, "heartbeat_at": now, "revision": state["revision"]}

    def create_task(
        self,
        title: str,
        scope: List[str],
        acceptance: List[str],
        priority: str = "P1",
        depends_on: Optional[List[str]] = None,
        reviewer: Optional[str] = None,
        created_by: str = "system",
        expected_revision: Optional[int] = None,
    ) -> Dict[str, Any]:
        if priority not in PRIORITIES:
            raise ValueError("invalid priority: %s" % priority)
        normalized_scope = normalize_paths(scope)
        task_id = new_id("task")
        now = utc_now()
        payload = {
            "task": {
                "id": task_id,
                "title": title,
                "status": "todo",
                "priority": priority,
                "scope": normalized_scope,
                "acceptance": list(acceptance or []),
                "depends_on": list(depends_on or []),
                "owner": None,
                "reviewer": reviewer,
                "created_by": created_by,
                "created_at": now,
                "updated_at": now,
            }
        }
        return self._single_event_write("task_created", payload, "tasks", task_id, expected_revision, actor=created_by)

    def claim_task(
        self,
        task_id: str,
        agent_id: str,
        file_patterns: List[str],
        lease_minutes: float = 30,
        expected_revision: Optional[int] = None,
    ) -> Dict[str, Any]:
        normalized_patterns = normalize_paths(file_patterns)
        expanded_paths, directory_claims = self._expand_patterns(normalized_patterns)
        claim_id = new_id("claim")
        now = utc_now()
        expires_at = add_minutes(lease_minutes)
        with self._locked():
            state = self.load_state()
            self._check_revision(state, expected_revision)
            task = self._find_task(state, task_id)
            self._find_agent(state, agent_id)
            expired_events = self._expire_due_claims(state, agent_id)
            conflicts = self._find_claim_conflicts(state, expanded_paths, directory_claims, exclude_claim_ids=[])
            if conflicts:
                raise ConflictError("active claim conflict", conflicts)
            warnings = self._dependency_warnings(state, task)
            claim = {
                "id": claim_id,
                "task_id": task_id,
                "agent_id": agent_id,
                "patterns": normalized_patterns,
                "expanded_paths": expanded_paths,
                "directory_claims": directory_claims,
                "status": "active",
                "created_at": now,
                "updated_at": now,
                "heartbeat_at": now,
                "expires_at": expires_at,
                "release_reason": None,
            }
            events = expired_events + [
                self._make_event(
                    "claim_created",
                    state,
                    {
                        "claim": claim,
                        "task_id": task_id,
                        "agent_id": agent_id,
                    },
                    actor=agent_id,
                    revision_offset=len(expired_events),
                )
            ]
            self._append_events_and_write_state(state, events)
        saved = self._find_claim(self.load_state(), claim_id)
        saved = dict(saved)
        saved["warnings"] = warnings
        return saved

    def release_claim(
        self,
        task_id: str,
        agent_id: str,
        reason: str = "done",
        expected_revision: Optional[int] = None,
    ) -> Dict[str, Any]:
        if reason not in RELEASE_REASONS:
            raise ValueError("invalid release reason: %s" % reason)
        with self._locked():
            state = self.load_state()
            self._check_revision(state, expected_revision)
            claims = [
                c
                for c in state["claims"]
                if c["task_id"] == task_id and c["agent_id"] == agent_id and c["status"] == "active"
            ]
            if not claims:
                raise InvalidOperationError("active claim not found")
            event = self._make_event(
                "claim_released",
                state,
                {"claim_id": claims[0]["id"], "reason": reason},
                actor=agent_id,
            )
            self._append_events_and_write_state(state, [event])
        return self._find_claim(self.load_state(), claims[0]["id"])

    def check_file_claims(self, paths: List[str]) -> Dict[str, Any]:
        normalized_paths = normalize_paths(paths)
        state = self.load_state()
        active = []
        for claim in state["claims"]:
            if claim["status"] != "active" or self._is_claim_expired(claim):
                continue
            for path in normalized_paths:
                if self._claim_covers_path(claim, path):
                    active.append(claim)
                    break
        return {"paths": normalized_paths, "active_claims": active, "revision": state["revision"]}

    def update_task(
        self,
        task_id: str,
        agent_id: str,
        status: str,
        note: Optional[str] = None,
        evidence: Optional[str] = None,
        expected_revision: Optional[int] = None,
    ) -> Dict[str, Any]:
        if status not in TASK_STATUSES:
            raise ValueError("invalid status: %s" % status)
        with self._locked():
            state = self.load_state()
            self._check_revision(state, expected_revision)
            task = self._find_task(state, task_id)
            agent = self._find_agent(state, agent_id)
            if status == "done":
                raise InvalidOperationError("use review_task to mark tasks done")
            self._assert_transition_allowed(task["status"], status)
            event = self._make_event(
                "task_updated",
                state,
                {"task_id": task_id, "status": status, "note": note, "evidence": evidence},
                actor=agent_id,
            )
            self._append_events_and_write_state(state, [event])
        return self._find_task(self.load_state(), task_id)

    def complete_task(
        self,
        task_id: str,
        agent_id: str,
        evidence: str,
        override_dependencies: bool = False,
        expected_revision: Optional[int] = None,
    ) -> Dict[str, Any]:
        with self._locked():
            state = self.load_state()
            self._check_revision(state, expected_revision)
            task = self._find_task(state, task_id)
            agent = self._find_agent(state, agent_id)
            if task.get("owner") != agent_id:
                raise InvalidOperationError("only task owner can complete task")
            missing = self._unfinished_dependencies(state, task)
            if missing and not (override_dependencies and agent["role"] == "coordinator"):
                raise InvalidOperationError("dependencies are not done", missing_dependencies=missing)
            if task["status"] != "in_progress":
                raise InvalidOperationError("task must be in_progress before complete")
            event = self._make_event(
                "task_completed",
                state,
                {"task_id": task_id, "evidence": evidence, "override_dependencies": override_dependencies},
                actor=agent_id,
            )
            self._append_events_and_write_state(state, [event])
        return self._find_task(self.load_state(), task_id)

    def review_task(
        self,
        task_id: str,
        reviewer_id: str,
        result: str,
        note: Optional[str] = None,
        expected_revision: Optional[int] = None,
    ) -> Dict[str, Any]:
        if result not in REVIEW_RESULTS:
            raise ValueError("invalid review result: %s" % result)
        with self._locked():
            state = self.load_state()
            self._check_revision(state, expected_revision)
            task = self._find_task(state, task_id)
            reviewer = self._find_agent(state, reviewer_id)
            if task["status"] != "review":
                raise InvalidOperationError("task is not in review")
            if task.get("owner") == reviewer_id and reviewer["role"] != "coordinator":
                raise InvalidOperationError("owner cannot approve own task")
            if result == "approved":
                allowed = {task.get("reviewer"), reviewer_id if reviewer["role"] in ("tester", "coordinator") else None}
                if reviewer_id not in allowed:
                    raise InvalidOperationError("reviewer is not allowed to approve task")
            event = self._make_event(
                "task_reviewed",
                state,
                {"task_id": task_id, "result": result, "note": note},
                actor=reviewer_id,
            )
            self._append_events_and_write_state(state, [event])
        return self._find_task(self.load_state(), task_id)

    def record_decision(
        self,
        title: str,
        decision: str,
        rationale: str,
        impact: Optional[str] = None,
        supersedes: Optional[str] = None,
        actor: str = "system",
        expected_revision: Optional[int] = None,
    ) -> Dict[str, Any]:
        decision_id = new_id("decision")
        payload = {
            "decision": {
                "id": decision_id,
                "title": title,
                "decision": decision,
                "rationale": rationale,
                "impact": impact,
                "supersedes": supersedes,
                "created_by": actor,
                "created_at": utc_now(),
            }
        }
        return self._single_event_write("decision_recorded", payload, "decisions", decision_id, expected_revision, actor)

    def record_handoff(
        self,
        agent_id: str,
        task_id: str,
        summary: str,
        changed_files: List[str],
        verification: str,
        open_issues: str,
        expected_revision: Optional[int] = None,
    ) -> Dict[str, Any]:
        normalized_files = normalize_paths(changed_files)
        handoff_id = new_id("handoff")
        with self._locked():
            state = self.load_state()
            self._check_revision(state, expected_revision)
            self._find_agent(state, agent_id)
            self._find_task(state, task_id)
            risks = []
            for path in normalized_files:
                if not self._agent_scope_covers_path(state, agent_id, path):
                    risks.append("out of agent scope: %s" % path)
                if not self._agent_claim_covers_path(state, agent_id, path):
                    risks.append("not covered by active claim: %s" % path)
            payload = {
                "handoff": {
                    "id": handoff_id,
                    "task_id": task_id,
                    "agent_id": agent_id,
                    "summary": summary,
                    "changed_files": normalized_files,
                    "verification": verification,
                    "open_issues": open_issues,
                    "risks": risks,
                    "created_at": utc_now(),
                }
            }
            event = self._make_event("handoff_recorded", state, payload, actor=agent_id)
            self._append_events_and_write_state(state, [event])
        return self._find_handoff(self.load_state(), handoff_id)

    def get_audit_log(self, since_revision: Optional[int] = None) -> Dict[str, Any]:
        events = self._read_events()
        if since_revision is not None:
            events = [e for e in events if e["revision"] > since_revision]
        return {"events": events, "revision": events[-1]["revision"] if events else self.load_state()["revision"]}

    def render_markdown(self, expected_revision: Optional[int] = None) -> Dict[str, Any]:
        with self._locked():
            state = self.load_state()
            self._check_revision(state, expected_revision)
            self.docs_dir.mkdir(parents=True, exist_ok=True)
            contents = {
                "AGENTS.md": self._render_agents(state),
                "TASK_BOARD.md": self._render_tasks(state),
                "DECISIONS.md": self._render_decisions(state),
                "HANDOFF_LOG.md": self._render_handoffs(state),
            }
            written = []
            skipped = []
            for filename, content in contents.items():
                path = self.docs_dir / filename
                if path.exists() and not path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
                    skipped.append(filename)
                    continue
                self._atomic_write_text(path, content)
                written.append(filename)
            return {"written": written, "skipped": skipped, "revision": state["revision"]}

    def _single_event_write(
        self,
        event_type: str,
        payload: Dict[str, Any],
        collection: str,
        item_id: str,
        expected_revision: Optional[int],
        actor: Optional[str] = None,
    ) -> Dict[str, Any]:
        with self._locked():
            state = self.load_state()
            self._check_revision(state, expected_revision)
            event = self._make_event(event_type, state, payload, actor=actor)
            self._append_events_and_write_state(state, [event])
        next_state = self.load_state()
        for item in next_state[collection]:
            if item["id"] == item_id:
                item = dict(item)
                item["_event_id"] = event["id"]
                return item
        raise InvalidOperationError("event did not create expected item")

    def _make_event(
        self,
        event_type: str,
        state: Dict[str, Any],
        payload: Dict[str, Any],
        actor: Optional[str] = None,
        revision_offset: int = 0,
    ) -> Dict[str, Any]:
        return {
            "id": new_id("evt"),
            "type": event_type,
            "revision": int(state.get("revision", 0)) + 1 + revision_offset,
            "actor": actor,
            "created_at": utc_now(),
            "payload": payload,
        }

    def _append_events_and_write_state(self, state: Dict[str, Any], events: List[Dict[str, Any]]) -> None:
        self.coord_dir.mkdir(parents=True, exist_ok=True)
        with self.events_path.open("a", encoding="utf-8") as fh:
            for event in events:
                fh.write(json.dumps(event, ensure_ascii=False, sort_keys=True) + "\n")
                self._apply_event(state, event)
            fh.flush()
            os.fsync(fh.fileno())
        self._atomic_write_json(self.state_path, state)

    def _read_events(self) -> List[Dict[str, Any]]:
        if not self.events_path.exists():
            return []
        events = []
        for line in self.events_path.read_text(encoding="utf-8").splitlines():
            if line.strip():
                events.append(json.loads(line))
        return events

    def _replay(self, events: List[Dict[str, Any]]) -> Dict[str, Any]:
        state = blank_state()
        for event in events:
            self._apply_event(state, event)
        return state

    def _apply_event(self, state: Dict[str, Any], event: Dict[str, Any]) -> None:
        payload = event["payload"]
        event_type = event["type"]
        if event_type == "workspace_initialized":
            state["goal"] = payload.get("goal", "")
        elif event_type == "agent_registered":
            state["agents"].append(payload["agent"])
        elif event_type == "task_created":
            state["tasks"].append(payload["task"])
        elif event_type == "claim_created":
            state["claims"].append(payload["claim"])
            task = self._find_task(state, payload["task_id"])
            task["owner"] = payload["agent_id"]
            task["updated_at"] = event["created_at"]
        elif event_type == "claim_expired":
            claim = self._find_claim(state, payload["claim_id"])
            claim["status"] = "expired"
            claim["release_reason"] = "expired"
            claim["updated_at"] = event["created_at"]
        elif event_type == "claim_released":
            claim = self._find_claim(state, payload["claim_id"])
            claim["status"] = "released"
            claim["release_reason"] = payload.get("reason", "done")
            claim["updated_at"] = event["created_at"]
        elif event_type == "task_updated":
            task = self._find_task(state, payload["task_id"])
            task["status"] = payload["status"]
            task["updated_at"] = event["created_at"]
            if payload["status"] == "done":
                task["reviewed_at"] = event["created_at"]
        elif event_type == "task_completed":
            task = self._find_task(state, payload["task_id"])
            task["status"] = "review"
            task["completed_at"] = event["created_at"]
            task["updated_at"] = event["created_at"]
        elif event_type == "task_reviewed":
            task = self._find_task(state, payload["task_id"])
            task["status"] = "done" if payload["result"] == "approved" else "in_progress"
            task["reviewed_at"] = event["created_at"] if payload["result"] == "approved" else task.get("reviewed_at")
            task["updated_at"] = event["created_at"]
        elif event_type == "decision_recorded":
            state["decisions"].append(payload["decision"])
        elif event_type == "handoff_recorded":
            state["handoffs"].append(payload["handoff"])
        else:
            raise InvalidOperationError("unknown event type: %s" % event_type)
        state["revision"] = event["revision"]
        state["last_event_id"] = event["id"]

    @contextmanager
    def _locked(self):
        self.coord_dir.mkdir(parents=True, exist_ok=True)
        acquired = False
        while not acquired:
            self._clean_stale_lock_if_possible()
            lock_data = {
                "pid": os.getpid(),
                "hostname": socket.gethostname(),
                "created_at": utc_now(),
                "expires_at": (
                    datetime.utcnow() + timedelta(seconds=self.lock_ttl_seconds)
                ).replace(microsecond=0).isoformat()
                + "Z",
                "owner": self.server_owner,
            }
            try:
                fd = os.open(str(self.lock_path), os.O_CREAT | os.O_EXCL | os.O_WRONLY)
                with os.fdopen(fd, "w", encoding="utf-8") as fh:
                    json.dump(lock_data, fh, sort_keys=True)
                acquired = True
            except FileExistsError:
                raise LockConflictError("workspace lock is held", conflicts=[self._read_lock_safely()])
        try:
            yield
        finally:
            try:
                current = self._read_lock_safely()
                if current.get("owner") == self.server_owner:
                    self.lock_path.unlink()
            except FileNotFoundError:
                pass

    def _clean_stale_lock_if_possible(self) -> None:
        if not self.lock_path.exists():
            return
        lock = self._read_lock_safely()
        expires_at = lock.get("expires_at")
        if expires_at:
            try:
                if parse_time(expires_at) < datetime.utcnow():
                    self.lock_path.unlink()
                    return
            except Exception:
                pass
        if lock.get("hostname") == socket.gethostname():
            pid = lock.get("pid")
            if isinstance(pid, int) and not self._pid_exists(pid):
                self.lock_path.unlink()

    def _read_lock_safely(self) -> Dict[str, Any]:
        try:
            return json.loads(self.lock_path.read_text(encoding="utf-8"))
        except Exception:
            return {"path": str(self.lock_path), "unreadable": True}

    @staticmethod
    def _pid_exists(pid: int) -> bool:
        if pid <= 0:
            return False
        try:
            os.kill(pid, 0)
            return True
        except ProcessLookupError:
            return False
        except PermissionError:
            return True

    def _atomic_write_json(self, path: Path, data: Dict[str, Any]) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_name(path.name + ".tmp-%s" % uuid.uuid4().hex)
        tmp.write_text(json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        os.replace(str(tmp), str(path))

    def _atomic_write_text(self, path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_name(path.name + ".tmp-%s" % uuid.uuid4().hex)
        tmp.write_text(content, encoding="utf-8")
        os.replace(str(tmp), str(path))

    def _check_revision(self, state: Dict[str, Any], expected_revision: Optional[int]) -> None:
        if expected_revision is not None and state["revision"] != expected_revision:
            raise RevisionConflictError(expected_revision, state["revision"])

    def _find_agent(self, state: Dict[str, Any], agent_id: str) -> Dict[str, Any]:
        for agent in state["agents"]:
            if agent["id"] == agent_id:
                return agent
        raise InvalidOperationError("agent not found: %s" % agent_id)

    def _find_task(self, state: Dict[str, Any], task_id: str) -> Dict[str, Any]:
        for task in state["tasks"]:
            if task["id"] == task_id:
                return task
        raise InvalidOperationError("task not found: %s" % task_id)

    def _find_claim(self, state: Dict[str, Any], claim_id: str) -> Dict[str, Any]:
        for claim in state["claims"]:
            if claim["id"] == claim_id:
                return claim
        raise InvalidOperationError("claim not found: %s" % claim_id)

    def _find_handoff(self, state: Dict[str, Any], handoff_id: str) -> Dict[str, Any]:
        for handoff in state["handoffs"]:
            if handoff["id"] == handoff_id:
                return handoff
        raise InvalidOperationError("handoff not found: %s" % handoff_id)

    def _expand_patterns(self, patterns: List[str]) -> Tuple[List[str], List[str]]:
        expanded = set()
        directories = set()
        for pattern in patterns:
            abs_pattern = str(self.root / pattern)
            matches = glob.glob(abs_pattern, recursive=True)
            if has_glob(pattern):
                directories.add(self._directory_claim_for_pattern(pattern))
            if not has_glob(pattern) and (self.root / pattern).is_dir():
                directories.add(pattern.rstrip("/"))
            for match in matches:
                path = Path(match)
                if path.is_file():
                    expanded.add(path.resolve().relative_to(self.root).as_posix())
                elif path.is_dir() and not has_glob(pattern):
                    directories.add(path.resolve().relative_to(self.root).as_posix())
            if not matches and not has_glob(pattern):
                expanded.add(pattern)
        return sorted(expanded), sorted(directories)

    @staticmethod
    def _directory_claim_for_pattern(pattern: str) -> str:
        parts = pattern.split("/")
        prefix = []
        for part in parts:
            if has_glob(part):
                break
            prefix.append(part)
        if not prefix and parts:
            return "."
        directory = "/".join(prefix)
        if directory.endswith("/**"):
            directory = directory[:-3]
        return directory.rstrip("/") or "."

    def _expire_due_claims(self, state: Dict[str, Any], actor: str) -> List[Dict[str, Any]]:
        events = []
        for claim in list(state["claims"]):
            if claim["status"] == "active" and self._is_claim_expired(claim):
                events.append(
                    self._make_event(
                        "claim_expired",
                        state,
                        {"claim_id": claim["id"]},
                        actor=actor,
                        revision_offset=len(events),
                    )
                )
        return events

    @staticmethod
    def _is_claim_expired(claim: Dict[str, Any]) -> bool:
        try:
            return parse_time(claim["expires_at"]) < datetime.utcnow()
        except Exception:
            return False

    def _find_claim_conflicts(
        self,
        state: Dict[str, Any],
        expanded_paths: List[str],
        directory_claims: List[str],
        exclude_claim_ids: List[str],
    ) -> List[Dict[str, Any]]:
        conflicts = []
        for claim in state["claims"]:
            if claim["id"] in exclude_claim_ids or claim["status"] != "active" or self._is_claim_expired(claim):
                continue
            for path in expanded_paths:
                if self._claim_covers_path(claim, path):
                    conflicts.append({"claim": claim, "path": path})
                    break
            else:
                for directory in directory_claims:
                    if self._directories_overlap(directory, claim.get("directory_claims", [])):
                        conflicts.append({"claim": claim, "directory": directory})
                        break
                    for path in claim.get("expanded_paths", []):
                        if self._path_under_directory(path, directory):
                            conflicts.append({"claim": claim, "directory": directory, "path": path})
                            break
        return conflicts

    @staticmethod
    def _path_under_directory(path: str, directory: str) -> bool:
        directory = directory.rstrip("/")
        if directory == ".":
            return True
        return path == directory or path.startswith(directory + "/")

    def _claim_covers_path(self, claim: Dict[str, Any], path: str) -> bool:
        if path in claim.get("expanded_paths", []):
            return True
        for directory in claim.get("directory_claims", []):
            if self._path_under_directory(path, directory):
                return True
        return False

    @staticmethod
    def _directories_overlap(directory: str, directories: List[str]) -> bool:
        directory = directory.rstrip("/")
        for existing in directories:
            existing = existing.rstrip("/")
            if directory == "." or existing == ".":
                return True
            if directory == existing or directory.startswith(existing + "/") or existing.startswith(directory + "/"):
                return True
        return False

    def _unfinished_dependencies(self, state: Dict[str, Any], task: Dict[str, Any]) -> List[str]:
        by_id = {t["id"]: t for t in state["tasks"]}
        return [dep for dep in task.get("depends_on", []) if by_id.get(dep, {}).get("status") != "done"]

    def _dependency_warnings(self, state: Dict[str, Any], task: Dict[str, Any]) -> List[str]:
        missing = self._unfinished_dependencies(state, task)
        if missing:
            return ["unfinished dependencies: %s" % ", ".join(missing)]
        return []

    @staticmethod
    def _assert_transition_allowed(current: str, target: str) -> None:
        if current == target:
            return
        if current == "done":
            raise InvalidOperationError("done tasks cannot transition")
        if target == "blocked" and current != "done":
            return
        if current == "blocked":
            if target == "in_progress":
                return
            raise InvalidOperationError("blocked can only return to in_progress")
        allowed = {
            "todo": {"in_progress"},
            "in_progress": {"review"},
            "review": {"done", "in_progress"},
        }
        if target not in allowed.get(current, set()):
            raise InvalidOperationError("invalid transition %s -> %s" % (current, target))

    @staticmethod
    def _scope_matches(scope_filter: List[str], task_scope: List[str]) -> bool:
        if not scope_filter:
            return True
        for candidate in task_scope:
            for pattern in scope_filter:
                if fnmatch.fnmatch(candidate, pattern) or fnmatch.fnmatch(pattern, candidate):
                    return True
        return False

    def _claim_matches_scope(self, claim: Dict[str, Any], scope_filter: List[str]) -> bool:
        if not scope_filter:
            return True
        paths = claim.get("expanded_paths", []) + claim.get("directory_claims", [])
        for path in paths:
            for pattern in scope_filter:
                if fnmatch.fnmatch(path, pattern) or self._path_under_directory(path, pattern.rstrip("/**")):
                    return True
        return False

    def _agent_scope_covers_path(self, state: Dict[str, Any], agent_id: str, path: str) -> bool:
        agent = self._find_agent(state, agent_id)
        return any(fnmatch.fnmatch(path, pattern) or self._path_under_directory(path, pattern.rstrip("/**")) for pattern in agent["scope"])

    def _agent_claim_covers_path(self, state: Dict[str, Any], agent_id: str, path: str) -> bool:
        for claim in state["claims"]:
            if claim["agent_id"] == agent_id and claim["status"] == "active" and self._claim_covers_path(claim, path):
                return True
        return False

    def _render_agents(self, state: Dict[str, Any]) -> str:
        lines = [GENERATED_MARKER, "", "# Agents", "", "Revision: `%s`" % state["revision"], ""]
        for agent in state["agents"]:
            lines += [
                "## %s" % html.escape(agent["display_name"]),
                "",
                "- id: `%s`" % agent["id"],
                "- role: `%s`" % agent["role"],
                "- status: `%s`" % agent["status"],
                "- scope: `%s`" % ", ".join(agent["scope"]),
                "- last heartbeat: `%s`" % agent["last_heartbeat_at"],
                "",
            ]
        return "\n".join(lines) + "\n"

    def _render_tasks(self, state: Dict[str, Any]) -> str:
        lines = [GENERATED_MARKER, "", "# Task Board", "", "Revision: `%s`" % state["revision"], ""]
        for status in ["todo", "in_progress", "blocked", "review", "done"]:
            lines += ["## %s" % status, ""]
            for task in [t for t in state["tasks"] if t["status"] == status]:
                lines += [
                    "- `%s` %s [%s] owner=`%s` reviewer=`%s`"
                    % (
                        task["id"],
                        html.escape(task["title"]),
                        task["priority"],
                        task.get("owner") or "",
                        task.get("reviewer") or "",
                    )
                ]
            lines.append("")
        return "\n".join(lines) + "\n"

    def _render_decisions(self, state: Dict[str, Any]) -> str:
        lines = [GENERATED_MARKER, "", "# Decisions", "", "Revision: `%s`" % state["revision"], ""]
        for decision in state["decisions"]:
            lines += [
                "## %s" % html.escape(decision["title"]),
                "",
                "- id: `%s`" % decision["id"],
                "- created_by: `%s`" % decision["created_by"],
                "- supersedes: `%s`" % (decision.get("supersedes") or ""),
                "",
                "**Decision**",
                safe_code_block(decision["decision"]),
                "",
                "**Rationale**",
                safe_code_block(decision["rationale"]),
                "",
                "**Impact**",
                safe_code_block(decision.get("impact")),
                "",
            ]
        return "\n".join(lines) + "\n"

    def _render_handoffs(self, state: Dict[str, Any]) -> str:
        lines = [GENERATED_MARKER, "", "# Handoff Log", "", "Revision: `%s`" % state["revision"], ""]
        for handoff in state["handoffs"]:
            lines += [
                "## %s" % handoff["id"],
                "",
                "- task: `%s`" % handoff["task_id"],
                "- agent: `%s`" % handoff["agent_id"],
                "- changed_files: `%s`" % ", ".join(handoff["changed_files"]),
                "- risks: `%s`" % "; ".join(handoff["risks"]),
                "",
                "**Summary**",
                safe_code_block(handoff["summary"]),
                "",
                "**Verification**",
                safe_code_block(handoff["verification"]),
                "",
                "**Open Issues**",
                safe_code_block(handoff["open_issues"]),
                "",
            ]
        return "\n".join(lines) + "\n"
